### PR TITLE
Uninstall ansible if version not same (needed to upgrade to 2.10)

### PR DESCRIPTION
**Pull request by seanwang-okta**
Need to update Ansible version to 2.10.5 or greater due to homebrew cask changes which is causing issues: https://github.com/ansible-collections/community.general/issues/1524

In order to update Ansible from 2.9.10 to 2.10, need to uninstall first, then reinstall: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-macos

### CODE REVIEW

**Review by lhazlewood — APPROVED** [review]
LGTM 👍

**Comment by seanwang-okta** [comment]
hey @lhazlewood can you merge this for me? i don't have write access.

**Comment by lhazlewood** [comment]
@seanwang-okta just invited you as a team member - please ensure you can merge :)

**Comment by seanwang-okta** [comment]
@lhazlewood i accepted the invitation but still unable to merge. Do I need to be granted explicit write access? thanks.

**Comment by seanwang-okta** [comment]
Screen Shot 2021-03-02 at 5 00 45 PM

**Review by lhazlewood — APPROVED** [review]

**Comment by lhazlewood** [comment]
Maybe it was just that someone needed to approve the review?

**Comment by seanwang-okta** [comment]
hmmm still doesn't work. i can see the approval but it still says "Only those with write access to this repository can merge pull requests."

**Comment by lhazlewood** [comment]
Just added write access - sorry!

**Comment by seanwang-okta** [comment]
awesome that worked, thanks @lhazlewood :)

**Pull request merged**
